apiVersion: v1
kind: Pod
metadata:
  name: pv-inspector
spec:
  containers:
    - name: inspector
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: local-path-pvc
